POST http://localhost:3000/posts
Content-Type: application/json

{"title":"My first Post",
"postType":"post",
"slug":"my-first-post",
"status":"draft",
"content":"I am Nsengi  great Dev of the 21st century",
"schema":"{\r\n \"@context\": \"https"\/\/schema.org\",\r\n \"@type\": \"Person\"\r\n}",
"featuredImageUrl":"",
"publishedOn": "2024-12-23T07:46:32+0000",
"tags":["nestjs","typescript"],
"metaOptions":[
    {"key":"","value":20}
]
}