POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUzLCJlbWFpbCI6Im1haWxAbWFpbC5jb20iLCJpYXQiOjE3MzQzNzUwMDcsImV4cCI6MTczNDM3ODYwNywiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.8TI5_-kalwJQ_GBT7OieEoh9Hdilfd4oHgZyWfGnScc

{"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUzLCJpYXQiOjE3MzQzNzUwMDcsImV4cCI6MTczNDQ2MTQwNywiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.InZmZ8l_kJBBTTixKUARHb2tOWQrcs7mhueIDzVoCIM"}